source("R/ui_helpers.R")   # must be first — modules depend on it

source("libraries.R")

### R/
source("R/data_manager/load_data.R")
source("R/data_manager/clean_data.R")
source("R/add_identifiers/convert_ids.R")
source("R/add_identifiers/add_go_annotations.R")
source("R/add_identifiers/import_corum.R")
source("R/enrichment/gost_analysis.R")
source("R/filtering/filter_go_proteins.R")
source("R/plotting/gost_plots.R")
source("R/plotting/heatmap_plots.R")
source("R/plotting/plot_store.R")
source("R/plotting/gosemsim_plots.R")
source("R/plotting/gsea_cnet_plots.R")
source("R/plotting/expression_heatmap.R")
source("R/corshift/corshift_analysis.R")

### modules/
source("modules/data_manager/load_data.R")
source("modules/data_manager/view_data.R")
source("modules/data_manager/save_data.R")
source("modules/data_manager/delete_data.R")
source("modules/data_manager/rename_data.R")
source("modules/data_manager/clean_data.R")
source("modules/add_identifiers/convert_ids.R")
source("modules/add_identifiers/add_go_annotations.R")
source("modules/add_identifiers/import_corum.R")
source("modules/enrichment/gost_analysis.R")
source("modules/filtering/filter_go_proteins.R")
source("modules/plotting/gost_plots.R")
source("modules/plotting/heatmap_plots.R")
source("modules/plotting/plot_viewer.R")
source("modules/plotting/gosemsim_plots.R")
source("modules/plotting/gsea_cnet_plots.R")
source("modules/plotting/expression_heatmap.R")
source("modules/plotting/corshift_heatmap.R")
source("modules/corshift/corshift_analysis.R")